---
- name: install nodejs with apt
  apt:
    update_cache: yes
    name: nodejs

- name: install npm with apt
  apt:
    update_cache: yes
    name: npm

- name: install pm2
  command: npm install pm2 -g 

- name: copy file
  copy:
    src: index.js
    dest: /tmp/nodejs
    mode: preserve
    
- name: serve file
  shell: pm2 start index.js
  args:
    chdir: /tmp/nodejs
