AWSTemplateFormatVersion: 2010-09-09
Description: provision an ec2 instance with keypair and security group

Parameters:
  Environment:
    Description: prefix for resources provisioned with this script
    Type: String
    Default: UdacityProject3
  VpcId:
    Description: vpc that the security group and ec2 instance should be created in
    Type: String
    Default: vpc-0104809558281317b
  KeyName:
    Description: keypair for the ec2 instance
    Type: String
    Default: UdacityProject3

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: allow http and ssh from anywhere
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: !Ref Environment
      VpcId: !Ref VpcId

  Server:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0d70546e43a941d70
      KeyName: !Ref KeyName
      InstanceType: t2.nano
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref SecurityGroup

