version: 2.1
executors:
  default: 
    docker: 
      - image: cimg/base:stable
commands: 
  install-aws:
    steps:
      - run: python3 --version
      - run: sudo apt-get -y install python3-pip

jobs:
  get-aws-version:
    executor: default
    steps:
      - install-aws
workflows:
  default:
    jobs:
      - get-aws-version

