version: 2.1
executors:
  default: 
    docker: 
      - image: cimg/base:stable-20.04
commands:
  install-dependencies:
    steps:
      - run: apt install aws-cli
      - run: apt install ansible
jobs:
  check:
    executor: default
    steps:
      - install-dependencies
workflows:
  default:
    jobs:
      - check

