version: 2.1
jobs:
  aws:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_DEFAULT_REGION: us-west-2
      AWS_ROLE_ARN: arn:aws:iam::726559158740:role/Udacitycicd
    steps:
      - run:
          name: authenticate
          command: |
            # use the OpenID Connect token to obtain AWS credentials
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
            $(aws sts assume-role-with-web-identity \
             --role-arn ${AWS_ROLE_ARN} \
             --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
             --web-identity-token $CIRCLE_OIDC_TOKEN \
             --duration-seconds 3600 \
             --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
             --output text)

            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

            echo $AWS_ACCESS_KEY_ID 
            echo $AWS_SECRET_ACCESS_KEY
            echo $AWS_SESSION_TOKEN

            aws sts get-caller-identity

            

workflows:
  play:
    jobs:
      - aws:
          context: 
            - aws-federation


