version: 2.1
jobs:
  aws:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_DEFAULT_REGION: us-west-2
      AWS_ROLE_ARN: arn:aws:iam::726559158740:role/Udacitycicd
    steps:
      - run:
          name: authenticate
          command: |
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
            $(aws sts assume-role-with-web-identity \
            --role-arn ${AWS_ROLE_ARN} \
            --role-session-name "CIRCLECI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
            --web-identity-token "${CIRCLE_OIDC_TOKEN}" \
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]')
            echo $AWS_ACCESS_KEY
            echo $AWS_SECRET_ACCESS_KEY 
            echo $AWS_SESSION_TOKEN

          
workflows:
  play:
    jobs:
      - aws:
          context: 
            - aws-federation


