version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@3.1.1
executors:
  default: 
    docker: 
      - image: cimg/base:stable
jobs:
  get-aws-version:
    executor: aws-cli/default
    steps:
      - run: aws --version
workflows:
  default:
    jobs:
      - get-aws-version

